# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dbac82454d312e75d6d177e8ce30f5d6d8302685cd8f3ea12df4b676acf1ab027ac4dbf84a0af4b9b9ac04e114aecc1f8f5ae6940d6db4afa6c5251d4249257

test:
  secret_key_base: 07b4683d85349f6f1dbd28a6e727dd4deee4635f237ebd3731a590c2ec8ea2bb0aa7f0c0953b3377c9266e4af730c803d024298d635f29db17dcf0b7280a8983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
